export const Mocks = {
  createMockConfig: () => ({
    GEMINI_API_KEY: 'test-api-key',
    gemini_model: 'gemini-2.5-flash',
    unprocessed_label: 'unprocessed',
    processed_label: 'processed',
    processing_failed_label: 'error',
    processing_frequency_in_minutes: 5,
    hour_of_day_to_run_sanity_checking: 0,
    go_link: '',
    max_threads: 50,
    default_task_list_name: 'My Tasks',
    task_service: 'Google Tasks',
    todoist_api_key: '',
    todoist_project_id: '',
  }),
  createMockGmailThread: (subject: string) => ({
    getFirstMessageSubject: () => subject,
    getId: () => 'thread-id',
    getMessages: () => [Mocks.getMockMessage({})],
    moveToInbox: jest.fn(),
    addLabel: jest.fn(),
    removeLabel: jest.fn(),
    markRead: jest.fn(),
    markUnread: jest.fn(),
    createDraftReply: jest.fn(),
    createDraftReplyAll: jest.fn(),
    getLabels: jest.fn(),
    getLastMessageDate: jest.fn(),
    getMessageCount: jest.fn(),
    getPermalink: jest.fn(),
    hasStarredMessages: jest.fn(),
    isImportant: jest.fn(),
    isInChats: jest.fn(),
    isInInbox: jest.fn(),
    isInSpam: jest.fn(),
    isInTrash: jest.fn(),
    isUnread: jest.fn(),
    moveToSpam: jest.fn(),
    refresh: jest.fn(),
    reply: jest.fn(),
    replyAll: jest.fn(),
  }),

  getMockThread: (overrides: any) => ({
    ...{
      getId: jest.fn(() => 'thread-id'),
      getFirstMessageSubject: jest.fn(() => 'Test Subject'),
      getMessages: jest.fn(() => []),
      removeLabel: jest.fn(),
      addLabel: jest.fn(),
      moveToArchive: jest.fn(),
      moveToInbox: jest.fn(),
      moveToTrash: jest.fn(),
      markRead: jest.fn(),
      markUnread: jest.fn(),
      createDraftReply: jest.fn(),
      createDraftReplyAll: jest.fn(),
      getLabels: jest.fn(() => []),
      getLastMessageDate: jest.fn(() => new Date()),
      getMessageCount: jest.fn(() => 1),
      getPermalink: jest.fn(() => ''),
      hasStarredMessages: jest.fn(() => false),
      isImportant: jest.fn(() => false),
      isInChats: jest.fn(() => false),
      isInInbox: jest.fn(() => false),
      isInSpam: jest.fn(() => false),
      isInTrash: jest.fn(() => false),
      isUnread: jest.fn(() => false),
      moveToSpam: jest.fn(),
      refresh: jest.fn(),
      reply: jest.fn(),
      replyAll: jest.fn(),
    },
    ...overrides,
  }),
  getMockLabel: (overrides: any) => ({
    ...{
      getName: () => 'Test Label',
      getThreads: () => [],
    },
    ...overrides,
  }),
  getMockMessage: (overrides: any) => ({
    ...{
      getDate: () => new Date(),
      getFrom: () => 'test@example.com',
      getTo: () => 'test@example.com',
      getSubject: () => 'Test Subject',
      getPlainBody: () => 'Test Body',
    },
    ...overrides,
  }),
  getMockSheet: (data: any[][]) => ({
    getDataRange: () => ({
      getValues: () => data,
      getDisplayValues: () => data,
    }),
  }),
  getMockSpreadsheet: (sheets: { [key: string]: any }) => ({
    getSheetByName: (name: string) => sheets[name],
    addDeveloperMetadata: () => {},
    addEditor: () => {},
    addEditors: () => {},
    addMenu: () => {},
    addViewer: () => {},
    addViewers: () => {},
    appendRow: () => {},
    copy: () => ({} as any),
    createDeveloperMetadataFinder: () => ({} as any),
    deleteActiveSheet: () => {},
    deleteColumn: () => {},
    deleteColumns: () => {},
    deleteRow: () => {},
    deleteRows: () => {},
    deleteSheet: () => {},
    duplicateActiveSheet: () => ({} as any),
    getActiveCell: () => ({} as any),
    getActiveRange: () => ({} as any),
    getActiveSheet: () => ({} as any),
    getBandings: () => [],
    getBlob: () => ({} as any),
    getColumnWidth: () => 0,
    getConditionalFormatRules: () => [],
    getDataRange: () => ({} as any),
    getDeveloperMetadata: () => [],
    getEditors: () => [],
    getFormUrl: () => '',
    getFrozenColumns: () => 0,
    getFrozenRows: () => 0,
    getId: () => '',
    getImages: () => [],
    getLastColumn: () => 0,
    getLastRow: () => 0,
    getName: () => '',
    getNumSheets: () => 0,
    getOwner: () => ({} as any),
    getPredefinedSpreadsheetThemes: () => [],
    getProtections: () => [],
    getRange: () => ({} as any),
    getRangeByName: () => ({} as any),
    getRowHeight: () => 0,
    getSheets: () => [],
    getSpreadsheetTheme: () => ({} as any),
    getSpreadsheetUrl: () => '',
    getTimeZone: () => '',
    getToken: () => '',
    getUrl: () => '',
    getViewers: () => [],
    hideSheet: () => {},
    insertColumnAfter: () => {},
    insertColumnBefore: () => {},
    insertColumnsAfter: () => {},
    insertColumnsBefore: () => {},
    insertImage: () => ({} as any),
    insertRowAfter: () => {},
    insertRowBefore: () => {},
    insertRowsAfter: () => {},
    insertRowsBefore: () => {},
    insertSheet: () => ({} as any),
    moveActiveSheet: () => {},
    moveChartToObjectSheet: () => ({} as any),
    removeEditor: () => {},
    removeMenu: () => {},
    removeNamedRange: () => {},
    removeViewer: () => {},
    rename: () => {},
    renameActiveSheet: () => {},
    resetSpreadsheetTheme: () => {},
    setActiveRange: () => ({} as any),
    setActiveSheet: () => ({} as any),
    setActiveSpreadsheet: () => {},
    setColumnWidth: () => {},
    setConditionalFormatRules: () => {},
    setFrozenColumns: () => {},
    setFrozenRows: () => {},
    setNamedRange: () => {},
    setRowHeight: () => {},
    setSpreadsheetTheme: () => {},
    setTimeZone: () => {},
    show: () => {},
    sort: () => {},
    toast: () => {},
    unhide: () => {},
    updateMenu: () => {},
    autoResizeColumn: () => {},
    createTextFinder: () => ({} as any),
    getActiveRangeList: () => ({} as any),
    getAs: () => ({} as any),
    getNamedRanges: () => [],
    getRangeList: () => ({} as any),
    getSheetId: () => 0,
    getSheetValues: () => [[]],
    getSlicer: () => ({} as any),
    getSlicers: () => [],
    getSupportedThemes: () => [],
    hideColumn: () => {},
    hideRow: () => {},
    insertChart: () => ({} as any),
    insertColumns: () => {},
    insertFilter: () => ({} as any),
    insertImageWithDescription: () => ({} as any),
    insertImageWithUrl: () => ({} as any),
    insertPivotTable: () => ({} as any),
    insertSlicer: () => ({} as any),
    isColumnHiddenByUser: () => false,
    isRowHiddenByFilter: () => false,
    isRowHiddenByUser: () => false,
    moveColumns: () => {},
    moveRows: () => {},
    protect: () => ({} as any),
    removeFilter: () => {},
    removeSlicer: () => {},
    setColumnWidths: () => {},
    setRowHeights: () => {},
    showColumn: () => {},
    showRow: () => {},
    unhideColumn: () => {},
    unhideRow: () => {},
    getCurrentCell: () => ({} as any),
    getDataSourceTables: () => [],
    getIterativeCalculationConvergenceThreshold: () => 0,
    getMaxIterativeCalculationCycles: () => 0,
    getRecalculationInterval: () => '',
    getSpreadsheetLocale: () => '',
    isIterativeCalculationEnabled: () => false,
    moveChartToObject: () => {},
    setIterativeCalculationConvergenceThreshold: () => {},
    setMaxIterativeCalculationCycles: () => {},
    setRecalculationInterval: () => {},
    setSpreadsheetLocale: () => {},
  }),
  createMockUrlFetchApp: () => ({
    fetch: jest.fn(() => Mocks.getMockUrlFetchResponse(200, '[]')),
    fetchAll: jest.fn(),
    getRequest: jest.fn(),
  }),

  getMockUrlFetchResponse: (code: number, content: string) => ({
    getResponseCode: () => code,
    getContentText: () => content,
    getAllHeaders: () => ({}),
    getAs: () => ({} as any),
    getBlob: () => ({} as any),
    getContent: () => [],
    getHeaders: () => ({}),
  }),
  getMockTask: (overrides: any) => ({
    ...{
      id: 'task-id',
      title: 'Test Task',
      notes: 'gmail_thread_id: thread-id',
      completed: null,
      due: null,
      hidden: false,
      parent: null,
      position: '0',
      status: 'needsAction',
      links: [],
      selfLink: '',
      updated: '',
    },
    ...overrides,
  }),
  createMockTask: (overrides: Partial<GoogleAppsScript.Tasks.Schema.Task>): GoogleAppsScript.Tasks.Schema.Task => ({
    id: `task-id-${Math.random()}`,
    title: 'Test Task',
    notes: 'Test Notes',
    updated: new Date().toISOString(),
    ...overrides,
  }),
  createMockTasks: (tasks: GoogleAppsScript.Tasks.Schema.Task[] = []): any => ({
    Tasklists: {
      list: jest.fn(() => ({ items: [Mocks.getMockTaskList({ title: 'My Tasks' })] })),
    },
    Tasks: {
      list: jest.fn(() => ({ items: tasks })),
      insert: jest.fn(),
      update: jest.fn(),
    },
  }),

  getMockTaskList: (overrides: any) => ({
    ...{
      id: 'task-list-id',
      title: 'Test Task List',
      selfLink: '',
      updated: '',
    },
    ...overrides,
  }),
};
